// Generated by scripts/doodles/build.mjs. Edit the script, not this file:
// `pnpm doodles:build` rewrites it. DESIGN.md section 4 sets the grammar.

import type { CSSProperties } from "react";

import { cn } from "@/lib/utils";

import { doodleProps, type DoodleProps, strokeAttributes } from "./doodle";
/**
 * A big four-point sparkle with a small one, the accent that also lights
 * every illustration. Filled with the current color.
 */
export function Sparkle(props: DoodleProps) {
  return (
    <svg {...doodleProps(props, "0 0 48 48")}>
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-0.4s",
            animationDuration: "5.4s",
            "--doodle-float": "-6px",
          } as CSSProperties
        }
      >
        <g>
          <path
            {...strokeAttributes}
            d="M21 9c0 13 5 18 18 18c-13 0-18 5-18 18c0-13-5-18-18-18c13 0 18-5 18-18z"
            fill="currentColor"
            stroke="none"
            style={
              {
                animationDelay: "0ms",
                "--draw-length": 119,
              } as CSSProperties
            }
          />
          <path
            {...strokeAttributes}
            d="M40 3c0 5 2 7 7 7c-5 0-7 2-7 7c0-5-2-7-7-7c5 0 7-2 7-7z"
            fill="currentColor"
            stroke="none"
            style={
              {
                animationDelay: "45ms",
                "--draw-length": 46,
              } as CSSProperties
            }
          />
        </g>
      </g>
    </svg>
  );
}

/**
 * A highlighter stroke behind one key word, in a soft amber unless the
 * caller sets another text color. Stretches to its container; place it
 * before the word in the DOM so the text paints on top.
 */
export function MarkerHighlight(props: DoodleProps) {
  return (
    <svg
      {...doodleProps(
        { ...props, className: cn("text-brand-soft-2", props.className) },
        "0 0 120 40",
      )}
      preserveAspectRatio="none"
    >
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-0.4s",
            animationDuration: "5.4s",
            "--doodle-float": "-6px",
          } as CSSProperties
        }
      >
        <g transform="rotate(-1.2 60 20)">
          <path
            {...strokeAttributes}
            d="M2 10.6C2.9 7,5.5 9.8,7.3 9.3C9 8.9,10.8 8.4,12.5 8C14.3 7.6,16.1 6.9,17.8 6.8C19.6 6.6,21.3 7.1,23.1 7C24.8 6.9,26.6 6.3,28.4 6.2C30.1 6.1,31.9 6.4,33.6 6.3C35.4 6.1,37.2 5.7,38.9 5.4C40.7 5.2,42.4 4.9,44.2 4.7C45.9 4.6,47.7 4.7,49.5 4.5C51.2 4.3,53 3.7,54.7 3.6C56.5 3.5,58.2 3.8,60 3.7C61.8 3.7,63.5 3.4,65.3 3.3C67 3.3,68.8 3.5,70.5 3.5C72.3 3.6,74.1 3.5,75.8 3.5C77.6 3.5,79.3 3.5,81.1 3.6C82.8 3.7,84.6 3.8,86.4 4.1C88.1 4.3,89.9 4.9,91.6 5.1C93.4 5.3,95.2 5.2,96.9 5.4C98.7 5.6,100.4 6,102.2 6.5C103.9 7,105.7 7.8,107.5 8.4C109.2 8.9,111 9.4,112.7 9.8C114.5 10.2,117.1 7.1,118 10.8C118.9 14.5,118.9 28.4,118 32.1C117.1 35.8,114.5 32.6,112.7 32.9C111 33.3,109.2 33.8,107.5 34.2C105.7 34.7,103.9 35.2,102.2 35.4C100.4 35.6,98.7 35.6,96.9 35.5C95.2 35.5,93.4 35.4,91.6 35.2C89.9 35,88.1 34.3,86.4 34.2C84.6 34,82.8 34.3,81.1 34.4C79.3 34.4,77.6 34.5,75.8 34.4C74.1 34.4,72.3 34.1,70.5 34C68.8 33.9,67 33.8,65.3 33.8C63.5 33.8,61.8 33.9,60 34C58.2 34,56.5 33.7,54.7 33.9C53 34,51.2 34.7,49.5 34.9C47.7 35.1,45.9 35.1,44.2 35.1C42.4 35.1,40.7 35,38.9 35.1C37.2 35.1,35.4 35,33.6 35.2C31.9 35.4,30.1 36,28.4 36.1C26.6 36.3,24.8 36,23.1 35.8C21.3 35.7,19.6 35.5,17.8 35.3C16.1 35.1,14.3 35.1,12.5 34.6C10.8 34.2,9 33.1,7.3 32.6C5.5 32,2.9 34.9,2 31.2C1.1 27.5,1.1 14.3,2 10.6Z"
            fill="currentColor"
            stroke="none"
            style={
              {
                animationDelay: "0ms",
                "--draw-length": 281,
              } as CSSProperties
            }
          />
        </g>
      </g>
    </svg>
  );
}

/**
 * A ring drawn once and a bit around a number or a short label, in the
 * brand color unless the caller sets another text color.
 */
export function CircleAround(props: DoodleProps) {
  return (
    <svg
      {...doodleProps(
        { ...props, className: cn("text-brand", props.className) },
        "0 0 120 60",
      )}
    >
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-0.4s",
            animationDuration: "5.4s",
            "--doodle-float": "-6px",
          } as CSSProperties
        }
      >
        <g transform="rotate(-4 60 30)">
          <path
            {...strokeAttributes}
            d="M11.7 36.2C11.6 35.6,10.8 33.9,10.6 32.7C10.4 31.6,10.5 30.4,10.7 29.2C10.9 28.1,11.4 26.9,12 25.8C12.7 24.6,13.5 23.5,14.6 22.4C15.6 21.3,16.8 20.3,18.3 19.2C19.7 18.2,21.4 17.2,23.2 16.3C25.1 15.4,27.1 14.6,29.3 13.8C31.6 13,34 12.3,36.5 11.8C39 11.2,41.7 10.7,44.5 10.3C47.2 9.9,50.1 9.7,52.9 9.5C55.8 9.4,58.7 9.3,61.6 9.4C64.5 9.5,67.4 9.7,70.2 9.9C73 10.2,75.7 10.6,78.3 11C81 11.5,83.5 12.1,86 12.7C88.4 13.3,90.7 14,92.9 14.8C95.1 15.5,97.2 16.4,99.1 17.3C101 18.2,102.7 19.1,104.3 20.1C105.9 21.2,107.3 22.2,108.4 23.3C109.6 24.5,110.6 25.6,111.3 26.8C112 28,112.4 29.3,112.6 30.5C112.8 31.7,112.7 33,112.3 34.2C111.9 35.5,111.2 36.7,110.3 37.9C109.4 39,108.2 40.2,106.8 41.3C105.3 42.4,103.6 43.4,101.8 44.4C100 45.3,97.9 46.2,95.7 47C93.5 47.9,91.1 48.6,88.6 49.3C86.2 49.9,83.6 50.5,80.9 51C78.3 51.5,75.5 51.9,72.7 52.2C69.9 52.5,66.9 52.8,64 52.9C61.1 53.1,58.1 53.1,55.2 53.1C52.2 53,49.2 52.9,46.3 52.6C43.4 52.4,40.5 52,37.7 51.5C34.9 51,32.2 50.5,29.6 49.8C27.1 49.1,24.7 48.3,22.5 47.4C20.3 46.5,18.3 45.5,16.5 44.5C14.7 43.5,13.2 42.4,11.9 41.2C10.6 40.1,9.6 38.9,8.7 37.7C7.9 36.4,7.4 35.2,7.1 33.9C6.7 32.7,6.7 31.4,6.8 30.2C6.9 28.9,7.3 27.7,7.8 26.4C8.4 25.2,9.2 24,10.2 22.8C11.2 21.6,12.4 20.4,13.9 19.3C15.3 18.2,17 17.1,18.8 16.1C20.7 15.1,24 13.7,25.1 13.3"
            style={
              {
                animationDelay: "0ms",
                "--draw-length": 274,
              } as CSSProperties
            }
          />
        </g>
      </g>
    </svg>
  );
}

/**
 * Arrow used with a handwritten caption. `curve` dives from the caption down
 * to something below it; `flat` runs sideways to something on the same line.
 * Both point right; mirror with `-scale-x-100` to point left.
 */
export function SketchArrow({
  shape = "curve",
  ...props
}: DoodleProps & { shape?: "curve" | "flat" }) {
  if (shape === "flat") {
    return (
      <svg {...doodleProps(props, "0 0 80 24")}>
        <path
          {...strokeAttributes}
          d="M4 15c12-7 26-9 40-6 11 2 20 3 30 2"
          style={{ "--draw-length": 72 } as CSSProperties}
        />
        <path
          {...strokeAttributes}
          d="M65 4l9 7-10 5"
          style={{ "--draw-length": 23 } as CSSProperties}
        />
      </svg>
    );
  }
  return (
    <svg {...doodleProps(props, "0 0 80 60")}>
      <path
        {...strokeAttributes}
        d="M6 9c14 2 32 7 45 22 4 5 7 10 9 16"
        style={{ "--draw-length": 70 } as CSSProperties}
      />
      <path
        {...strokeAttributes}
        d="M52 42l9 5-1-11"
        style={{ "--draw-length": 21 } as CSSProperties}
      />
    </svg>
  );
}
