// Generated by scripts/doodles/build.mjs. Edit the script, not this file:
// `pnpm doodles:build` rewrites it. DESIGN.md section 4 sets the grammar.

import type { CSSProperties } from "react";

import { doodleProps, type DoodleProps, strokeAttributes } from "./doodle";

/** Artboard shared by every spot illustration. */
export const spotViewBox = "0 0 320 220";
/**
 * Two speech bubbles: a five-star Testimonial with two lines of
 * handwriting, and a smaller bubble with quotation marks behind it.
 */
export function SpeechBubbleStars(props: DoodleProps) {
  return (
    <svg {...doodleProps(props, "0 0 320 220")}>
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-0.4s",
            animationDuration: "5.4s",
            "--doodle-float": "-6px",
          } as CSSProperties
        }
      >
        <g transform="rotate(3 242 74)">
          <path
            {...strokeAttributes}
            d="M210 44C227 44,258 44.1,276 44Q290 44,290 58C290.2 63.8,290.2 83.6,290 90Q290 104,276 104Q254 104.4,232 104Q221 113,206 122Q209 115,214 104Q212 104,210 104Q196 104,196 90C195.2 83.6,196.1 63.8,196 58Q196 44,210 44Z"
            fill="var(--surface)"
          />
          <path
            {...strokeAttributes}
            d="M224 66c-4 1-6 5-5 9 1 3 4 4 7 3 3-2 2-6-1-7M240 66c-4 1-6 5-5 9 1 3 4 4 7 3 3-2 2-6-1-7"
          />
        </g>
      </g>
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-1.7000000000000002s",
            animationDuration: "6.300000000000001s",
            "--doodle-float": "-4px",
          } as CSSProperties
        }
      >
        <g transform="rotate(-2 130 128)">
          <path
            {...strokeAttributes}
            d="M56 70C99.4 70.2,158.8 69.9,204 70Q220 70,220 86C220 105,220.6 140,220 160Q220 176,204 176Q149 175.9,94 176Q81 188,64 200Q67 190,72 176Q64 176.2,56 176Q40 176,40 160C40.3 140,39.4 105,40 86Q40 70,56 70Z"
            fill="var(--surface)"
          />
          <path
            {...strokeAttributes}
            d="M74.4 102L76.7 109L84.4 109L78.2 113.5L80.4 120.5L73.7 116.5L68.4 120.5L69.2 113.5L64.4 109L70.7 109ZM98.4 102L100.7 109L108.4 109L102.2 113.5L104.4 120.5L97.7 116.5L92.4 120.5L93.2 113.5L88.4 109L94.7 109ZM122.4 102L124.7 109L132.4 109L126.2 113.5L128.4 120.5L121.7 116.5L116.4 120.5L117.2 113.5L112.4 109L118.7 109ZM146.4 102L148.7 109L156.4 109L150.2 113.5L152.4 120.5L145.7 116.5L140.4 120.5L141.2 113.5L136.4 109L142.7 109ZM170.4 102L172.7 109L180.4 109L174.2 113.5L176.4 120.5L169.7 116.5L164.4 120.5L165.2 113.5L160.4 109L166.7 109Z"
            fill="var(--brand)"
          />
          <path
            {...strokeAttributes}
            d="M72 142Q81.7 141.2,91.3 142Q101 142.8,110.7 142Q120.3 141.2,130 142Q139.7 142.8,149.3 142Q159 141.2,168.7 142Q178.3 142.8,188 142"
          />
          <path
            {...strokeAttributes}
            d="M72 156Q81.8 155.2,91.5 156Q101.3 156.8,111 156Q120.8 155.2,130.5 156Q140.3 156.8,150 156"
          />
        </g>
      </g>
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-3s",
            animationDuration: "7.2s",
            "--doodle-float": "-6px",
          } as CSSProperties
        }
      >
        <g>
          <path
            {...strokeAttributes}
            d="M30 40c0 4.3 1.7 6 6 6c-4.3 0-6 1.7-6 6c0-4.3-1.7-6-6-6c4.3 0 6-1.7 6-6z"
            fill="var(--brand)"
          />
          <path
            {...strokeAttributes}
            d="M300 143c0 5 2 7 7 7c-5 0-7 2-7 7c0-5-2-7-7-7c5 0 7-2 7-7z"
            fill="var(--brand)"
          />
          <path
            {...strokeAttributes}
            d="M268 20c0 2.9 1.1 4 4 4c-2.9 0-4 1.1-4 4c0-2.9-1.1-4-4-4c2.9 0 4-1.1 4-4z"
            fill="var(--brand)"
          />
        </g>
      </g>
    </svg>
  );
}

/**
 * Camera on a tripod, recording light on.
 */
export function CameraTripod(props: DoodleProps) {
  return (
    <svg {...doodleProps(props, "0 0 320 220")}>
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-0.4s",
            animationDuration: "5.4s",
            "--doodle-float": "-6px",
          } as CSSProperties
        }
      >
        <g>
          <path {...strokeAttributes} d="M160 170v14" />
          <path {...strokeAttributes} d="M160 184c-14 12-28 24-42 36" />
          <path {...strokeAttributes} d="M160 184c14 12 28 24 42 36" />
          <path {...strokeAttributes} d="M160 184v34" />
          <path
            {...strokeAttributes}
            d="M112 218l8 4M208 218l-8 4M154 218h12"
          />
          <path
            {...strokeAttributes}
            d="M166 184C165.71 187.31,163.31 189.7,160 190C156.69 190.09,153.86 187.31,154 184C153.88 180.69,156.69 177.8,160 178C163.31 178.01,166.32 180.69,166 184Z"
            fill="var(--surface)"
          />
          <path {...strokeAttributes} d="M126 78l8-14h52l8 14" />
          <path {...strokeAttributes} d="M98 78v-8h18v8" />
          <path
            {...strokeAttributes}
            d="M94 78C132.8 78.6,185.6 77.1,226 78Q240 78,240 92C240.4 108.4,239.5 138.7,240 156Q240 170,226 170C185.6 169.3,132.8 170.9,94 170Q80 170,80 156C80.6 138.7,80 108.4,80 92Q80 78,94 78Z"
            fill="var(--surface)"
          />
          <path
            {...strokeAttributes}
            d="M190 124C190.17 140.56,176.56 153.69,160 154C143.44 153.97,130.11 140.56,130 124C130.34 107.44,143.44 93.8,160 94C176.56 94.24,189.81 107.44,190 124Z"
            fill="var(--surface)"
          />
          <path
            {...strokeAttributes}
            d="M178 124C177.78 133.94,169.94 142.2,160 142C150.06 141.76,142.15 133.94,142 124C141.91 114.06,150.06 106.01,160 106C169.94 106.31,178.19 114.06,178 124Z"
          />
          <path {...strokeAttributes} d="M147 115c3-5 8-8 14-9" />
          <path
            {...strokeAttributes}
            d="M219 98C219.28 100.76,216.76 103.29,214 103C211.24 103.1,209.22 100.76,209 98C209.15 95.24,211.24 92.8,214 93C216.76 92.87,219.01 95.24,219 98Z"
            fill="var(--brand)"
          />
          <path {...strokeAttributes} d="M96 100h10M96 108h6" />
        </g>
      </g>
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-1.7000000000000002s",
            animationDuration: "6.300000000000001s",
            "--doodle-float": "-4px",
          } as CSSProperties
        }
      >
        <g>
          <path
            {...strokeAttributes}
            d="M274 53c0 5 2 7 7 7c-5 0-7 2-7 7c0-5-2-7-7-7c5 0 7-2 7-7z"
            fill="var(--brand)"
          />
          <path
            {...strokeAttributes}
            d="M52 145c0 3.6 1.4 5 5 5c-3.6 0-5 1.4-5 5c0-3.6-1.4-5-5-5c3.6 0 5-1.4 5-5z"
            fill="var(--brand)"
          />
        </g>
      </g>
    </svg>
  );
}

/**
 * Sealed envelope with a postmark and a star stamp.
 */
export function EnvelopeStamp(props: DoodleProps) {
  return (
    <svg {...doodleProps(props, "0 0 320 220")}>
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-0.4s",
            animationDuration: "5.4s",
            "--doodle-float": "-6px",
          } as CSSProperties
        }
      >
        <g transform="rotate(-2 160 126)">
          <path
            {...strokeAttributes}
            d="M56 60C120.6 60,197.1 60.9,264 60Q276 60,276 72C275.1 103.6,276.4 147.1,276 180Q276 192,264 192C197.1 191.5,120.6 192.2,56 192Q44 192,44 180C43.4 147.1,44.8 103.6,44 72Q44 60,56 60Z"
            fill="var(--surface)"
          />
          <path
            {...strokeAttributes}
            d="M46 66C90 96,128 124,160 148C192 124,230 96,274 66"
          />
          <path {...strokeAttributes} d="M46 188C74 166,98 148,118 132" />
          <path {...strokeAttributes} d="M274 188C246 166,222 148,202 132" />
          <path
            {...strokeAttributes}
            d="M168 88Q177.5 87.2,187 88Q196.5 88.8,206 88"
          />
          <path
            {...strokeAttributes}
            d="M176 98Q183.5 97.2,191 98Q198.5 98.8,206 98"
          />
          <path
            {...strokeAttributes}
            d="M217 72C229.2 72.3,244.4 72,257 72Q260 72,260 75C260.2 85.2,260.5 98.4,260 109Q260 112,257 112C244.4 111.5,229.2 112.4,217 112Q214 112,214 109C214.8 98.4,214.7 85.2,214 75Q214 72,217 72Z"
            fill="var(--surface)"
          />
          <path
            {...strokeAttributes}
            d="M221 77C230.9 77.8,242.8 76.5,253 77Q255 77,255 79C255.2 86.9,255.5 96.8,255 105Q255 107,253 107C242.8 106.3,230.9 107,221 107Q219 107,219 105C218.4 96.8,219.3 86.9,219 79Q219 77,221 77Z"
          />
          <path
            {...strokeAttributes}
            d="M237.4 81L240 88.7L248.4 88.7L241.6 93.7L244 101.3L236.7 97L230.8 101.3L231.7 93.7L226.4 88.7L233.4 88.7Z"
            fill="var(--brand)"
          />
        </g>
      </g>
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-1.7000000000000002s",
            animationDuration: "6.300000000000001s",
            "--doodle-float": "-4px",
          } as CSSProperties
        }
      >
        <g>
          <path
            {...strokeAttributes}
            d="M300 39c0 5 2 7 7 7c-5 0-7 2-7 7c0-5-2-7-7-7c5 0 7-2 7-7z"
            fill="var(--brand)"
          />
          <path
            {...strokeAttributes}
            d="M30 195c0 3.6 1.4 5 5 5c-3.6 0-5 1.4-5 5c0-3.6-1.4-5-5-5c3.6 0 5-1.4 5-5z"
            fill="var(--brand)"
          />
        </g>
      </g>
    </svg>
  );
}

/**
 * The same envelope on its way, climbing to the right: the speed lines
 * trail from its lower-left corner, along the line of flight, the middle
 * one longest. For the moment an email has just gone out.
 */
export function EnvelopeSent(props: DoodleProps) {
  return (
    <svg {...doodleProps(props, "0 0 320 220")}>
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-0.4s",
            animationDuration: "5.4s",
            "--doodle-float": "-6px",
          } as CSSProperties
        }
      >
        <g>
          <path
            {...strokeAttributes}
            d="M40 127C43.2 126.6,52.7 125.4,59 124.4C65.3 123.4,74.8 121.6,78 121"
          />
          <path
            {...strokeAttributes}
            d="M12 149C17.8 148.4,35.3 146.9,47 145.6C58.7 144.3,76.2 141.8,82 141"
          />
          <path
            {...strokeAttributes}
            d="M34 171C38.3 170.5,51.3 169.3,60 168.1C68.7 166.9,81.7 164.7,86 164"
          />
        </g>
      </g>
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-1.7000000000000002s",
            animationDuration: "6.300000000000001s",
            "--doodle-float": "-4px",
          } as CSSProperties
        }
      >
        <g transform="rotate(-5 198 111)">
          <path
            {...strokeAttributes}
            d="M111 54C164.7 53.2,229.4 54.6,285 54Q296 54,296 65C295.2 91.6,296.8 129.2,296 157Q296 168,285 168C229.4 167.2,164.7 168.1,111 168Q100 168,100 157C99.2 129.2,100.5 91.6,100 65Q100 54,111 54Z"
            fill="var(--surface)"
          />
          <path
            {...strokeAttributes}
            d="M102 60C139 85,171 109,198 134C225 114,257 90,294 60"
          />
          <path {...strokeAttributes} d="M102 160C126 141,146 126,163 113" />
          <path {...strokeAttributes} d="M294 160C270 141,250 126,233 113" />
          <path
            {...strokeAttributes}
            d="M205 78Q213 77.2,221 78Q229 78.8,237 78"
          />
          <path
            {...strokeAttributes}
            d="M211 86Q217.5 85.2,224 86Q230.5 86.8,237 86"
          />
          <path
            {...strokeAttributes}
            d="M247 64C256.9 64.1,269.7 64.8,280 64Q283 64,283 67C283.3 75.2,283.8 86.4,283 95Q283 98,280 98C269.7 98.4,256.9 98.6,247 98Q244 98,244 95C244.9 86.4,244.1 75.2,244 67Q244 64,247 64Z"
            fill="var(--surface)"
          />
          <path
            {...strokeAttributes}
            d="M250 68C257.9 67.4,267.8 68.6,276 68Q278 68,278 70C277.3 76.3,278 84.5,278 91Q278 93,276 93C267.8 93,257.9 93.8,250 93Q248 93,248 91C248.5 84.5,248.5 76.3,248 70Q248 68,250 68Z"
          />
          <path
            {...strokeAttributes}
            d="M263.4 71.5L265.6 78.2L272.9 78.2L267 82.4L269.1 89.1L262.7 85.3L257.7 89.1L258.4 82.4L253.9 78.2L259.9 78.2Z"
            fill="var(--brand)"
          />
        </g>
      </g>
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-3s",
            animationDuration: "7.2s",
            "--doodle-float": "-6px",
          } as CSSProperties
        }
      >
        <g>
          <path
            {...strokeAttributes}
            d="M298 28c0 4.3 1.7 6 6 6c-4.3 0-6 1.7-6 6c0-4.3-1.7-6-6-6c4.3 0 6-1.7 6-6z"
            fill="var(--brand)"
          />
          <path
            {...strokeAttributes}
            d="M44 75c0 3.6 1.4 5 5 5c-3.6 0-5 1.4-5 5c0-3.6-1.4-5-5-5c3.6 0 5-1.4 5-5z"
            fill="var(--brand)"
          />
        </g>
      </g>
    </svg>
  );
}

/**
 * A wall of customer proof: a text Testimonial with its five stars, a
 * video Testimonial and a short quote, pinned at slight angles.
 */
export function WallFrames(props: DoodleProps) {
  return (
    <svg {...doodleProps(props, "0 0 320 220")}>
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-0.4s",
            animationDuration: "5.4s",
            "--doodle-float": "-6px",
          } as CSSProperties
        }
      >
        <g transform="rotate(-6 72 158)">
          <path
            {...strokeAttributes}
            d="M34 122C56.4 121.1,86.7 121.2,110 122Q118 122,118 130C118.9 145.8,118.4 169.5,118 186Q118 194,110 194C86.7 194,56.4 193.8,34 194Q26 194,26 186C25.9 169.5,25.5 145.8,26 130Q26 122,34 122Z"
            fill="var(--surface)"
          />
          <path
            {...strokeAttributes}
            d="M44 140c-4 1-6 5-5 9 1 3 4 4 7 3 3-2 2-6-1-7M60 140c-4 1-6 5-5 9 1 3 4 4 7 3 3-2 2-6-1-7"
          />
          <path
            {...strokeAttributes}
            d="M44 162Q54 161.2,64 162Q74 162.8,84 162Q94 161.2,104 162"
          />
          <path
            {...strokeAttributes}
            d="M44 172Q55.5 171.2,67 172Q78.5 172.8,90 172"
          />
          <path
            {...strokeAttributes}
            d="M44 182Q51 181.2,58 182Q65 182.8,72 182"
          />
        </g>
      </g>
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-1.7000000000000002s",
            animationDuration: "6.300000000000001s",
            "--doodle-float": "-4px",
          } as CSSProperties
        }
      >
        <g transform="rotate(4 258 98)">
          <path
            {...strokeAttributes}
            d="M219 32C241.7 32.1,273.4 32.4,297 32Q306 32,306 41C305.6 75.6,305.4 119.1,306 155Q306 164,297 164C273.4 164.5,241.7 164,219 164Q210 164,210 155C209.5 119.1,209.8 75.6,210 41Q210 32,219 32Z"
            fill="var(--surface)"
          />
          <path
            {...strokeAttributes}
            d="M273 88C272.86 96.28,266.28 103.02,258 103C249.72 102.86,243.33 96.28,243 88C242.82 79.72,249.72 73.26,258 73C266.28 72.78,272.75 79.72,273 88Z"
          />
          <path {...strokeAttributes} d="M253 80l12 8-12 8z" />
          <path
            {...strokeAttributes}
            d="M222 134Q231 133.2,240 134Q249 134.8,258 134Q267 133.2,276 134"
          />
          <path
            {...strokeAttributes}
            d="M222 144Q230 143.2,238 144Q246 144.8,254 144"
          />
        </g>
      </g>
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-3s",
            animationDuration: "7.2s",
            "--doodle-float": "-6px",
          } as CSSProperties
        }
      >
        <g transform="rotate(-2.5 130 121)">
          <path
            {...strokeAttributes}
            d="M61 62C103.5 61.4,155 61.6,199 62Q208 62,208 71C208.1 100.9,208.5 139.9,208 171Q208 180,199 180C155 179.2,103.5 180.7,61 180Q52 180,52 171C52.1 139.9,52.2 100.9,52 71Q52 62,61 62Z"
            fill="var(--surface)"
          />
          <path
            {...strokeAttributes}
            d="M87 88C87.13 94.07,82.07 99.33,76 99C69.93 99.09,65.29 94.07,65 88C65.23 81.93,69.93 76.68,76 77C82.07 76.77,86.9 81.93,87 88Z"
          />
          <path
            {...strokeAttributes}
            d="M94 84Q103 83.2,112 84Q121 84.8,130 84Q139 83.2,148 84"
          />
          <path
            {...strokeAttributes}
            d="M94 93Q102.5 92.2,111 93Q119.5 93.8,128 93"
          />
          <path
            {...strokeAttributes}
            d="M76.2 106.4L77.5 110.3L81.8 110.3L78.4 112.8L79.6 116.8L75.8 114.5L72.9 116.8L73.3 112.8L70.6 110.3L74.2 110.3ZM90.2 106.4L91.5 110.3L95.8 110.3L92.4 112.8L93.6 116.8L89.8 114.5L86.9 116.8L87.3 112.8L84.6 110.3L88.2 110.3ZM104.2 106.4L105.5 110.3L109.8 110.3L106.4 112.8L107.6 116.8L103.8 114.5L100.9 116.8L101.3 112.8L98.6 110.3L102.2 110.3ZM118.2 106.4L119.5 110.3L123.8 110.3L120.4 112.8L121.6 116.8L117.8 114.5L114.9 116.8L115.3 112.8L112.6 110.3L116.2 110.3ZM132.2 106.4L133.5 110.3L137.8 110.3L134.4 112.8L135.6 116.8L131.8 114.5L128.9 116.8L129.3 112.8L126.6 110.3L130.2 110.3Z"
            fill="var(--brand)"
          />
          <path
            {...strokeAttributes}
            d="M76 131Q85.5 130.2,95 131Q104.5 131.8,114 131Q123.5 130.2,133 131Q142.5 131.8,152 131Q161.5 130.2,171 131Q180.5 131.8,190 131"
          />
          <path
            {...strokeAttributes}
            d="M76 142Q86.2 141.2,96.4 142Q106.6 142.8,116.8 142Q127 141.2,137.2 142Q147.4 142.8,157.6 142Q167.8 141.2,178 142"
          />
          <path
            {...strokeAttributes}
            d="M76 153Q85.5 152.2,95 153Q104.5 153.8,114 153Q123.5 152.2,133 153Q142.5 153.8,152 153"
          />
        </g>
      </g>
      <g
        className="doodle-item"
        style={
          {
            animationDelay: "-4.300000000000001s",
            animationDuration: "8.100000000000001s",
            "--doodle-float": "-4px",
          } as CSSProperties
        }
      >
        <g>
          <path
            {...strokeAttributes}
            d="M34 45c0 5 2 7 7 7c-5 0-7 2-7 7c0-5-2-7-7-7c5 0 7-2 7-7z"
            fill="var(--brand)"
          />
          <path
            {...strokeAttributes}
            d="M186 23c0 3.6 1.4 5 5 5c-3.6 0-5 1.4-5 5c0-3.6-1.4-5-5-5c3.6 0 5-1.4 5-5z"
            fill="var(--brand)"
          />
          <path
            {...strokeAttributes}
            d="M300 190c0 4.3 1.7 6 6 6c-4.3 0-6 1.7-6 6c0-4.3-1.7-6-6-6c4.3 0 6-1.7 6-6z"
            fill="var(--brand)"
          />
        </g>
      </g>
    </svg>
  );
}
