/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/delivery/wrangler.jsonc --include-runtime=false workers/delivery/env.d.ts` (hash: eba03eeca0437aa8d2664e83c0cc4934)
interface __BaseEnv_Env {
	PUBLICATIONS: KVNamespace;
	ASSETS: Fetcher;
	ENVIRONMENT: "staging" | "local";
	ALLOWED_ORIGINS: "http://127.0.0.1:8790";
	CLOUDFLARE_CANARY_PUBLISH_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface StagingEnv {
		PUBLICATIONS: KVNamespace;
		ASSETS: Fetcher;
		ENVIRONMENT: "staging";
		ALLOWED_ORIGINS: "http://127.0.0.1:8790";
		CLOUDFLARE_CANARY_PUBLISH_SECRET: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "ALLOWED_ORIGINS" | "CLOUDFLARE_CANARY_PUBLISH_SECRET">> {}
}
